### ISSUE TITLE
How to convert the .pkl file to .png

### ISSUE THREAD

**Issue by kennyorn1** [Cuberick-Orion/CIRR#10]
How to convert .pkl file to .png
My research needs .png file not the .pkl file
![1673353569115](https://user-images.githubusercontent.com/110704880/211551613-01dfa94d-f998-4323-b84d-82457192e3cf.jpg)

**Comment by Cuberick-Orion** [comment]
Hi Kenny,

The short answer is you can't. The `.pkl` files are features extracted from backbone.

Please refer to the `README.md` file for details on obtaining the original image files.

Best,
David.

**Comment by kennyorn1** [comment]
> 

Thanks

> Hi Kenny,
> 
> The short answer is you can't. The `.pkl` files are features extracted from backbone.
> 
> Please refer to the `README.md` file for details on obtaining the original image files.
> 
> Best, David.


Thanks a lot!!!!
