### ISSUE TITLE
How to download raw images in a more faster way?

### ISSUE THREAD

**Issue by kennyorn1** [Cuberick-Orion/CIRR#11]
I found two ways to download raw images.
The first one is downloading through URLs, which have terrible disadvantages. 
The  other way is sending my request to [Google Form](https://goo.gl/forms/yS29stWnFWzrDBFH3), but does it really need a week to reply me? I hope it can be faster. Thanks a lot!!!
![A](https://user-images.githubusercontent.com/110704880/211724064-e1857755-980b-4e73-8852-3bf47ae63095.png)

**Comment by develop-productivity** [comment]
Hi, i receieved the reply, But I don't know how to select the subset contained in CIRR. Can you help me?

**Comment by develop-productivity** [comment]
我已经下载这个NLVR2的数据集了，然后这个CIRR数据集应该怎么划分那？文中说这个CIRR是NLVR2的子集

**Comment by HaHaJun1101** [comment]
> > 我已经下载这个NLVR2的数据集了，然后这个CIRR数据集应该怎么划分那？文中说这个CIRR是NLVR2的子集
> 
> 数据集有了然后跟着readme文档里的操作来弄就好了吧。我后面没弄下去，不太清楚具体咋弄的。

请问有后续了么 那个CIRR的caption和split文件到底是怎么搞到的呀

**Comment by Cuberick-Orion** [comment]
Hi,

Please see our README file on obtaining the annotations.

Best,
David.
