### ISSUE TITLE
Encounter Error when upload test result to server

### ISSUE THREAD

**Issue by BUAADreamer** [Cuberick-Orion/CIRR#13]
![image](https://user-images.githubusercontent.com/64362896/224877260-a33db9be-c063-4e64-97b7-7e5774d54c72.png)

**Comment by onevae** [comment]
me too. How did you deal with it?

**Comment by onevae** [comment]
ok! Thanks!!

**Comment by Cuberick-Orion** [comment]
Duplicate of #15
