### ISSUE TITLE
the inquiry of downloading json file

### ISSUE THREAD

**Issue by gersys** [Cuberick-Orion/CIRR#19]
Hi I'm Cheol-Ho Cho, PhD candidate at Sungkyunkwan University in Korea

I want to download the label and caption JSON file of CIRR.

However, there occur some error from the command below

```
mkdir data
cd data

git clone -b cirr_dataset git@github.com:Cuberick-Orion/CIRR.git cirr
```

How can I obtain the annotation file...?

the error message is below

```
root@b8d0f0e4cfd7:/project/Research/lincir/data# git clone -b cirr_dataset git@github.com:Cuberick-Orion/CIRR.git cirr
Cloning into 'cirr'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by Cuberick-Orion** [comment]
Hi,

I think this is more likely a git credential issue on your end. Could you check if you are able to clone any (arbitrary) other public repository?

**Comment by gersys** [comment]
I solved the problem by the command below

```
git clone -b cirr_dataset https://github.com/Cuberick-Orion/CIRR.git cirr
```

This is using HTTPS instead of SSH

Thank you for kind reply 😄
