### ISSUE TITLE
Could you provide the subset filtering code ? 

### ISSUE THREAD

**Issue by Yang-bug-star** [Cuberick-Orion/CIRR#20]

**Comment by Cuberick-Orion** [comment]
Hi,

Just checking what do you require, because the subset image ids are in the provided `json` files. In practice we didn't perform specific filtering to obtain the image sets that correspond to, say, the subset metric -- if that's what you mean.

**Comment by Yang-bug-star** [comment]
Your paper mentions that  “Once constructed we further filter the collection subsets
 to avoid heavy overlap”. I just want to know the exact filtering strategy here.

**Comment by Cuberick-Orion** [comment]
> Your paper mentions that “Once constructed we further filter the collection subsets to avoid heavy overlap”. I just want to know the exact filtering strategy here, e.g. the threshold you define a heavy overlap. Do you just compare image subset (a group of six) pairwise to filter out the subset with the larger index if their overlap exceeds a certain threshold?

I see what you meant. Yes, that is indeed what we did.

It has been a long time but if memory serves, we set a threshold of two or three images (out of six images that is). If say, one subset overlaps with another subset and exceeds such a threshold, we randomly remove one of them. We perform pairwise comparisons over all subsets.

**Comment by Yang-bug-star** [comment]
Thank you for your helpful response! It's really nice to get such great support. Much appreciated!
