### ISSUE TITLE
Some questions about paper

### ISSUE THREAD

**Issue by harukaza** [Cuberick-Orion/CIRR#5]
Thank you for sharing your work. I'm confused about some of the content in the paper. Is the vision-and-language (VLP) multi-layer transformers pre-trained? What pretraining model was used and what dataset was the pretraining done?

**Comment by Cuberick-Orion** [comment]
Hi Harukaza,

Yes, the VLP model is pre-trained. We used [OSCAR](https://github.com/microsoft/Oscar). In theory, you can try other pre-trained VLP as well.

For OSCAR pre-training, please refer to its paper (it involves a number of Vision-and-Language datasets).

**Comment by harukaza** [comment]
Thank you for your quick reply
