### ISSUE TITLE
Number of validation samples in annotations

### ISSUE THREAD

**Issue by hassony2** [Cuberick-Orion/CIRR#8]
Thank you very much for contributing this great dataset !

As far as I can see in the (recently downloaded annots) there are 4_181 samples and not 4_184 pairs as mentionned in the paper (table 2) for the validation split.
Could you let me know if this the correct number of expected samples for this split ?

Have a great day !

Yana

**Comment by Cuberick-Orion** [comment]
Hi Yana,

Thank you for noticing that -- it appears to be a typo in the paper.

The correct number of samples (i.e., pairs) in the validation split is 1,481.

We will see to correct the paper (on arXiv at least) shorty.

Best,
David.

**Comment by hassony2** [comment]
Thank you for the super fast answer and for clarifying this ! 

Have a great day :)

**Comment by Cuberick-Orion** [comment]
No worries, we have since updated the README file to include a note on the typo.
